const TRANSLATIONS: Record<string, Record<string, string>> = {
  ar: {
    "COLLECTIONS": "المجموعات",
    "WATCHES": "الساعات",
    "HOME": "الرئيسية",
    "EXPLORE": "استكشف",
    "JOURNAL": "المجلة",
    "TESTIMONIALS": "الشهادات",
    "BLOG": "المجلة",
    "WHATSAPP SUPPORT": "دعم واتساب",
    "WHATSAPP": "واتساب",
    "VIEW SPECS": "عرض المواصفات",
    "VIEW COLLECTION": "عرض المجموعة",
    "ORDER SECURELY VIA WHATSAPP": "اطلب بأمان عبر الواتساب",
    "BACK TO ALL COLLECTIONS": "العودة إلى جميع المجموعات",
    "EXPLORE MORE FROM": "استكشف المزيد من",
    "Exclusive Price": "السعر الحصري",
    "VAT INCLUDED": "شامل ضريبة القيمة المضافة",
    "HOVER OR CLICK TO ZOOM": "مرر الماوس أو انقر للتكبير",
    "CLICK IMAGE TO ZOOM OUT": "انقر على الصورة للتصغير",
    "RETRIEVING SPECIFICATIONS...": "جاري جلب المواصفات...",
    "2-YEAR SERVICE WARRANTY": "ضمان خدمة لمدة سنتين",
    "Protection standard": "معيار الحماية",
    "Same Day Delivery": "توصيل في نفس اليوم",
    "Same-Day Free Delivery": "توصيل مجاني بنفس اليوم",
    "SAME-DAY FREE DELIVERY": "توصيل مجاني بنفس اليوم",
    "LOCAL COURIER USP": "خدمة التوصيل المحلي المميزة",
    "FAST GLOBAL SHIPPING": "شحن عالمي سريع",
    "DHL & FEDEX EXPRESS": "دي إتش إل وفيدكس إكسبريس",
    "DUTY-FREE GUARANTEE": "ضمان معفى من الرسوم",
    "FOR MEN": "للرجال",
    "FOR LADIES": "للسيدات",
    "FOR WOMEN": "للنساء",
    "FOR MEN & LADIES": "للرجال وللسيدات",
    "FOR MEN & WOMEN": "للرجال والنساء",
    "FOR HIM": "للرجال",
    "FOR HER": "للسيدات",
    "SPECIAL SELECTION": "تشكيلة خاصة",
    "EXCLUSIVE MODELS": "موديلات حصرية",
    "CURATED FOR YOU": "مختارة خصيصاً لك",
    "SECURE INSURED PARTNERS": "شركاء شحن مؤمّنون وموثوقون",
    "SWISS | PRECISION": "الدقة | السويسرية",
    "SWISS PRECISION": "الدقة السويسرية",
    "SWISS": "سويسري",
    "PRECISION": "الدقة",
    "SUPER CLONE WATCHES DUBAI": "ساعات سوبر كلون دبي",
    "SUPER CLONE WATCHES IN DUBAI": "ساعات سوبر كلون في دبي",
    "Best replica watches in Dubai. Super clone watches & clone watches.": "أفضل ساعات السوبر كلون في دبي. ساعات طبق الأصل وساعات كلون.",
    "BEST REPLICA WATCHES IN DUBAI. SUPER CLONE WATCHES & CLONE WATCHES.": "أفضل ساعات السوبر كلون في دبي. ساعات طبق الأصل وساعات كلون.",
    "Best replica watches in Dubai. Master copy watches & clone watches.": "أفضل ساعات السوبر كلون في دبي. ساعات طبق الأصل وساعات كلون.",
    "BEST REPLICA WATCHES IN DUBAI. MASTER COPY WATCHES & CLONE WATCHES.": "أفضل ساعات السوبر كلون في دبي. ساعات طبق الأصل وساعات كلون.",
    "Super Clone": "سوبر كلون",
    "SUPER CLONE": "سوبر كلون",
    "super clone": "سوبر كلون",
    "Super clone": "سوبر كلون",
    "Super Clones": "ساعات سوبر كلون",
    "Dubai's ultimate boutique for 1:1 super clone watches. Hand-calibrated with flawless sweep movements, premium Oystersteel, and sapphire crystals. Cash on delivery available.": "بوتيك دبي الرائد لساعات السوبر كلون ١:١. معايرة يدوياً بحركات انسيابية متقنة، وفولاذ أويسترستيل الفاخر، وزجاج السافير. الدفع عند الاستلام متوفر.",
    "DUBAI EDITION": "إصدار دبي",
    "PREMIUM OYSTERSTEEL": "فولاذ أويسترستيل فاخر",
    "1:1 BUILD": "صناعة ١:١",
    "SWISS 1:1 BUILD": "صناعة سويسرية ١:١",
    "FREE": "مجانًا",
    "Same-day delivery": "توصيل في نفس اليوم",
    "2 YR": "سنتين",
    "Service warranty": "ضمان الخدمة",
    "COD": "الدفع عند الاستلام",
    "Multiple payments": "طرق دفع متعددة",
    "Brand": "الماركة",
    "Model": "الموديل",
    "Reference": "الرقم المرجعي",
    "Material": "المادة",
    "Size": "المقاس",
    "Movement": "الحركة",
    "Caliber": "العيار",
    "Bezel Configuration": "تكوين الإطار",
    "Crystal Glass": "زجاج الكريستال",
    "Water Testing": "فحص مقاومة الماء",
    "Service Warranty": "ضمان الخدمة",
    "SWISS MOVEMENT": "حركة سويسرية",
    "Automatic Caliber": "كاليبر أوتوماتيكي",
    "904L OYSTERSTEEL": "فولاذ أويسترستيل 904L",
    "Corrosion Resistant": "مقاوم للتآكل",
    "SAPPHIRE CRYSTAL": "زجاج سافير",
    "Scratch Proof": "مقاوم للخدش",
    "WATER RESISTANT": "مقاوم للماء",
    "Pressure Tested": "مفحوص تحت الضغط",
    "ARCHITECTURE": "هندسة",
    "OF TIME": "الوقت",
    "ARCHITECTURE OF TIME": "هندسة الوقت",
    "CASE, DIAL, MOVEMENT": "العلبة، الميناء، الحركة",
    "CASE": "العلبة",
    "DIAL": "الميناء",
    "Discover the best copy watches and super clone watches in Dubai, crafted with replica-watch detailing, refined case architecture, exposed movement depth, and polished gold finishing for collectors seeking premium replica watches in Dubai.": "اكتشف أفضل الساعات الماستر كوبي وساعات السوبر كلون في دبي، المصنوعة بتفاصيل دقيقة، وهيكل علبة راقٍ، وعمق حركة مكشوف، وتشطيبات ذهبية مصقولة لهواة الساعات الفاخرة في دبي.",
    "Discover the ultimate collection of superclone watches and superclone watches in Dubai. At Dubai Watches Gallery, we offer the finest superclone watches Dubai has ever seen, engineered with 1:1 replica-watch detailing, refined case architecture, exposed mechanical caliber movement depth, and polished gold finishing. We are the leading source for collectors seeking premium replica watches in Dubai and authentic-weight Dubai replica watches, fully calibrated for daily-wear precision.": "اكتشف المجموعة النهائية من ساعات السوبر كلون وساعات السوبر كلون في دبي. في معرض دبي للساعات، نقدم أفضل ساعات السوبر كلون التي شهدتها دبي على الإطلاق، والمصممة بتفاصيل ساعات تقليدية ١:١، وهيكل علبة راقٍ، وعمق حركة ميكانيكي مكشوف، وتشطيب ذهبي مصقول. نحن المصدر الرائد لهواة جمع الساعات الباحثين عن ساعات تقليدية ممتازة في دبي وساعات دبي التقليدية ذات الوزن الأصلي والمعايرة بالكامل لدقة الارتداء اليومي.",
    "At Dubai Watches Gallery, the engineering of our master copy timepieces represents the ultimate synthesis of form and function. Discover the finest selection of superclone watches and premium superclone watches in Dubai, meticulously crafted to replicate original luxury standards. As the premier destination for superclone watches Dubai collectors trust, each watch features a 1:1 case architecture, scratch-resistant sapphire glass, and a fully calibrated clone movement. For those seeking the highest quality replica watches in Dubai, our collection delivers identical luxury weights and detailed hand-finishing, making us the benchmark for Dubai replica watches and premium copy watches.": "في معرض دبي للساعات، تمثل هندسة ساعاتنا الماستر كوبي التكامل الأمثل بين الشكل والأداء. اكتشف أرقى تشكيلة من ساعات السوبر كلون وساعات السوبر كلون في دبي، المصممة بدقة لتحاكي المعايير الفاخرة الأصلية. بصفتنا الوجهة الأولى لساعات السوبر كلون التي يثق بها هواة الجمع في دبي، تتميز كل ساعة بهيكل علبة ١:١، وزجاج سافير مقاوم للخدش، وحركة كلون معايرة بالكامل لدقة الاستخدام اليومي.",
    "DWG": "معرض دبي للساعات",
    "ATELIER": "المشغل",
    "At Dubai Watches Gallery, we offer the best replica watches in Dubai. Our dedicated watchmaking atelier is specializing in the selection, calibration, and tuning of 1:1 super clone watches Dubai collectors cherish. Every super clone watch in Dubai that we hand-deliver is built using identical weight distribution and flawless Swiss sweep movements.": "في معرض دبي للساعات، نقدم أفضل الساعات الماستر كوبي في دبي. يتخصص مشغل الساعات المخصص لدينا في اختيار ومعايرة وضبط ساعات السوبر كلون ١:١ التي يفضلها جامعو الساعات في دبي. كل ساعة سوبر كلون في دبي نقوم بتسليمها يدويًا مصممة باستخدام توزيع وزن متطابق وحركات مسح سويسرية خالية من العيوب.",
    "As a premier source for copy watches Dubai and copy watches in Dubai, our in-house watchmakers specialize in tuning and recalibrating first copy movements. From disassembling to lubricating, each timepiece is optimized to replicate the fluid sweeps, tick rates, and robustness of original luxury brands.": "بصفتنا مصدرًا رئيسيًا لساعات الكوبي في دبي، يتخصص صانعو الساعات لدينا في ضبط وإعادة معايرة حركات الفيرست كوبي. من التفكيك إلى التشحيم، يتم تحسين كل ساعة لتكرار عمليات المسح الانسيابية ومعدلات التكتكة ومتانة الماركات الفاخرة الأصلية.",
    "From Daytona configurations to complex NTPT carbon fiber builds, we represent the peak of master copy watches Dubai has to offer. We use high-end 904L anti-corrosive steel, sapphire glass, and heavy bracelets to ensure our clone watches Dubai collection stands out.": "من تكوينات دايتونا إلى إصدارات ألياف الكربون NTPT المعقدة، نحن نمثل قمة ساعات الماستر كوبي التي تقدمها دبي. نحن نستخدم فولاذ 904L الراقي المقاوم للتآكل، وزجاج السافير، والأساور الثقيلة لضمان تميز مجموعة الساعات الكلون في دبي.",
    "FROM THE EYES OF THE ARTISAN": "من منظور الحرفي",
    "Every custom timepiece undergoes calibration and pressure testing to ensure confident daily precision": "تخضع كل ساعة مخصصة للمعايرة واختبار الضغط لضمان الدقة اليومية الموثوقة",
    "NEW ARRIVALS": "وصل حديثاً",
    "EXQUISITE CRAFTSMANSHIP": "حرفية استثنائية",
    "BEST SELLER": "الأكثر مبيعًا",
    "NEW ARRIVAL": "وصل حديثًا",
    "EXQUISITE": "استثنائي",
    "CRAFTSMANSHIP": "الحرفية",
    "Spotlight": "تحت الضوء",
    "Explore our latest curated timepieces, featuring ultra-precise movements, custom engineering, and original weight specifications.": "استكشف أحدث ساعاتنا المختارة بحركات فائقة الدقة وهندسة مخصصة ومواصفات وزن مطابقة.",
    "Hover to focus / click arrows to slide": "مرّر للتركيز / انقر الأسهم للتنقل",
    "Click arrows to slide": "انقر الأسهم للتنقل",
    "1:1 Swiss Super Clone Edition": "إصدار سوبر كلون سويسري ١:١",
    "1:1 Super Clone Edition": "إصدار سوبر كلون ١:١",
    "1:1 Flyback Chrono Super Clone": "كرونوغراف فلايباك سوبر كلون ١:١",
    "1:1 Swiss Master Copy Edition": "إصدار سوبر كلون سويسري ١:١",
    "1:1 Master Copy Edition": "إصدار سوبر كلون ١:١",
    "1:1 Flyback Chrono Master Copy": "كرونوغراف فلايباك سوبر كلون ١:١",
    "ALL BRANDS": "جميع الماركات",
    "ALL CATEGORIES": "جميع الفئات",
    "MENS": "رجالي",
    "WOMENS": "نسائي",
    "ALL": "الكل",
    "Search by model, brand, category, or style...": "البحث عن طريق الموديل، الماركة، الفئة، أو الطراز...",
    "Search Timepieces": "البحث في الساعات",
    "Filter by Brand": "تصفية حسب الماركة",
    "Filter by Model": "تصفية حسب الموديل",
    "Close filters": "إغلاق التصفية",
    "Master Copy": "سوبر كلون",
    "master copy": "سوبر كلون",
    "More Brands": "المزيد من الماركات",
    "Collection": "المجموعة",
    "TECHNICAL SPECIFICATIONS": "المواصفات الفنية",
    "DOSSIER DESCRIPTION": "وصف الملف",
    "Specifications": "المواصفات",
    "Description": "الوصف",
    "No reviews yet": "لا توجد مراجعات بعد",
    "Write a review": "اكتب مراجعة",
    "No reviews have been written yet. Be the first to share your thoughts!": "لم يتم كتابة أي مراجعات بعد. كن أول من يشارك أفكاره!",
    "Show Original": "عرض الأصلي",
    "IN STOCK": "متوفر",
    "In stock": "متوفر",
    "SIGNATURE TIMEPIECE": "ساعة مميزة",
    "LOAD MORE WATCHES": "تحميل المزيد من الساعات",
    "NO WATCHES MATCHING YOUR SEARCH. PLEASE BROWSE ALL BRAND PILLS.": "لا توجد ساعات تطابق بحثك. يرجى تصفح أزرار الماركات أعلاه.",
    "Select a brand to view available model variants.": "اختر ماركة لعرض الموديلات المتوفرة.",
    "Suggestions by Brand": "اقتراحات حسب الماركة",
    "Suggestions by Range": "اقتراحات حسب التشكيلة",
    "Curated Combinations": "تشكيلة مختارة",
    "ALL COMBINATIONS": "جميع التشكيلات",
    "MIXED BRANDS": "ماركات متنوعة",
    "All Combinations": "جميع التشكيلات",
    "1:1 Super Clone": "سوبر كلون 1:1",
    "Same-Day Delivery": "توصيل بنفس اليوم",
    "ACCESSORIES": "الملحقات",
    "Accessories": "الملحقات",
    "WATCH ACCESSORIES": "ملحقات الساعات",
    "STRAPS & LUXURY": "أساور وعلب فاخرة",
    "BOXES": "التقديم الفاخرة",
    "ALL ACCESSORIES": "جميع الملحقات",
    "Straps": "أساور وأحزمة",
    "Boxes": "علب فاخرة",
    "DUBAI WATCHES GALLERY": "معرض دبي للساعات",
    "Dubai Watches Gallery": "معرض دبي للساعات",
    "ORDER VIA WHATSAPP": "طلب عبر واتساب",
    "Complete your collection with premium replacement straps and authentic luxury watch presentation boxes.": "أكمل مجموعتك بأساور بديلة فاخرة وعلب تقديم الساعات الراقية.",
    "No accessories found in this category.": "لا توجد ملحقات متوفرة في هذا القسم حالياً.",
    "SHOWING": "عرض",
    "OF": "من",
    "HIGH-QUALITY MODELS AVAILABLE": "موديل عالي الجودة متاح",
    "WHITE GLOVE DELIVERY": "توصيل فاخر وفوري",
    "SAME-DAY FREE DELIVERY IN DUBAI & UAE": "توصيل مجاني بنفس اليوم في دبي والإمارات",
    "Direct hand-delivery across Dubai, Abu Dhabi, Sharjah, and all Emirates with zero advance payment.": "توصيل يدوي مباشر في دبي وأبوظبي والشارقة وجميع الإمارات دون أي دفع مسبق.",
    "Dubai Watches Gallery delivery promise": "وعد معرض دبي للساعات للتوصيل",
    "From Dubai.": "من دبي.",
    "To your wrist.": "إلى معصمك.",
    "QC checked before dispatch": "فحص الجودة قبل الشحن",
    "Secure presentation packaging": "تغليف فاخر وآمن",
    "Dubai priority": "أولوية دبي",
    "Free UAE delivery": "توصيل مجاني داخل الإمارات",
    "United Arab Emirates": "الإمارات العربية المتحدة",
    "GCC destinations": "وجهات الخليج",
    "Regional shipping": "شحن إقليمي",
    "International desk": "خدمة دولية",
    "Delivery to the USA": "توصيل إلى الولايات المتحدة",
    "Confirm your destination": "أكّد وجهة التوصيل",
    "Ask our team for your delivery window.": "اسأل فريقنا عن موعد التوصيل المتاح.",
    "Delivery support": "دعم التوصيل",
    "Order confirmation, QC review, and complimentary delivery across Dubai on eligible orders.": "تأكيد الطلب ومراجعة الجودة وتوصيل مجاني داخل دبي للطلبات المؤهلة.",
    "Secure, carefully packed delivery throughout the UAE with no additional delivery charge.": "توصيل آمن ومغلف بعناية إلى جميع أنحاء الإمارات دون رسوم إضافية.",
    "Tracked shipping to Saudi Arabia, Qatar, Kuwait, Bahrain, and Oman.": "شحن قابل للتتبع إلى السعودية وقطر والكويت والبحرين وعُمان.",
    "Door-to-door international dispatch supported by our Dubai team.": "شحن دولي من الباب إلى الباب بدعم من فريقنا في دبي.",
    "Complimentary same-day delivery in Dubai, free delivery across the UAE, and secure worldwide shipping to the USA and GCC countries.": "توصيل مجاني في اليوم نفسه داخل دبي، وتوصيل مجاني في الإمارات، وشحن عالمي آمن إلى الولايات المتحدة ودول الخليج.",
    "CELEBRITY MATCHES": "ساعات المشاهير",
    "CELEBRITY": "المشاهير",
    "MATCHES": "المطابقة",
    "AS SEEN ON ICONS": "كما ارتداها المشاهير",
    "DISCOVER TIMEPIECES WORN BY GLOBAL LEADERS, ATHLETES, AND ARTISTS": "اكتشف الساعات التي يرتديها القادة والرياضيون والفنانون حول العالم",
    "Worn by": "يرتديها",
    "Icons": "المشاهير",
    "Exact reference match": "تطابق دقيق مع الموديل",
    "Seen on": "شوهدت مع",
    "Editorial source": "المصدر التحريري",
    "Available reference": "الموديل المتاح",
    "View watch": "عرض الساعة",
    "Shop the edit": "تسوّق الاختيارات",
    "The moment on the wrist. The exact reference beside it. Four personalities, matched to four editions available in our store.": "لحظة مميزة على المعصم، والموديل المطابق بجانبها. أربع شخصيات وأربعة إصدارات متاحة في متجرنا.",
    "The matching watch": "الساعة المطابقة",
    "Available edition": "الإصدار المتاح",
    "Shop this watch": "تسوّق هذه الساعة",
    "DWG Icon Edit · 2026": "تحرير أيقونات دي دبليو جي · 2026",
    "Editorial source · ": "المصدر التحريري · ",
    "DWG catalogue edition": "إصدار كتالوج دي دبليو جي",
    "Editorial watch-spotting only. Celebrity images show original references; no affiliation or endorsement of Dubai Watches Gallery is implied.": "لرصد الساعات التحريرية فقط. تُظهر صور المشاهير الموديلات الأصلية؛ ولا يُقصد بها أي انتساب أو تأييد لمعرض دبي للساعات.",
    "How to Choose a Premium Replica Watch in Dubai": "كيف تختار ساعة ماستر كوبي فاخرة في دبي",
    "A complete quality-control guide covering the reference, movement, dial, crystal, case finishing, bracelet feel, fit, delivery, and after-sales support.": "دليل شامل لمراقبة الجودة يغطي الرقم المرجعي، الحركة، الميناء، الزجاج، تشطيب العلبة، ملمس السوار، المقاس، التوصيل، وخدمة ما بعد البيع.",
    "The Architecture of a 1:1 Clone Movement": "هندسة حركة الساعات الكلون ١:١",
    "An engineering explainer detailing how modern clone calibers reproduce the balance assembly, bridge architecture, rotor winding, and beat rate of Swiss movements.": "شرح هندسي يوضح كيف تحاكي عيارات الكلون الحديثة مجمع التوازن، وهيكل الجسور، وتعبئة الدوار، ومعدل النبض للحركات السويسرية.",
    "Rolex Daytona Reference Guide: Selecting the Right Dial and Caliber": "دليل مرجع رولكس دايتونا: اختيار الميناء والعيار المناسبين",
    "Explore the differences between steel, ceramic, Oysterflex, and precious-metal Daytona references with buying advice for collectors in Dubai.": "استكشف الفروق بين إصدارات دايتونا المصنوعة من الفولاذ، السيراميك، أويسترفليكس، والمعادن الثمينة مع نصائح شراء لهواة الجمع في دبي.",
    "Caring for High-End Replica Watches in Dubai's Climate": "العناية بالساعات الماستر كوبي الفاخرة في مناخ دبي",
    "Practical ownership rules covering heat, humidity, dust exposure, magnetic fields, bracelet cleaning, and scheduled service intervals.": "قواعد عملية للملكية تغطي الحرارة، الرطوبة، التعرض للغبار، المجالات المغناطيسية، تنظيف السوار، وجداول الصيانة الدورية.",
    "Mechanical vs. Automatic vs. Quartz: A Practical Collector's Guide": "الميكانيكية مقابل الأوتوماتيكية مقابل الكوارتز: دليل عملي لهواة الجمع",
    "Understand the mechanical heart of luxury timepieces, how automatic rotors function, and why sweep movements remain the collector standard.": "افهم القلب الميكانيكي للساعات الفاخرة، وكيف تعمل الدوارات الأوتوماتيكية، ولماذا تظل حركات المسح الانسيابية معيار هواة الجمع.",
    "The Essential 3-Watch Replica Collection for Every Occasion": "المجموعة الأساسية المكونة من 3 ساعات ماستر كوبي لكل مناسبة",
    "How to build a complete watch wardrobe with one daily sports piece, one formal dress reference, and one expressive weekend chronograph.": "كيفية بناء خزانة ساعات متكاملة بساعة رياضية يومية، وساعة رسمية للمناسبات، وكرونوغراف مميز لعطلة نهاية الأسبوع.",
    "Buying Guides": "أدلة الشراء",
    "Reference Guides": "أدلة المراجع",
    "Watch Care": "العناية بالساعات",
    "Watch Knowledge": "ثقافة الساعات",
    "Style Guides": "أدلة الأناقة",
    "Collector Guides": "أدلة هواة الجمع",
    "Dubai Watches Gallery Editorial": "تحرير معرض دبي للساعات",
    "Begin with the exact reference": "ابدأ بالرقم المرجعي الدقيق",
    "Inspect the dial and crystal": "افحص الميناء والزجاج",
    "Test the movement and controls": "اختبر الحركة وعناصر التحكم",
    "Evaluate finishing, weight, and comfort": "قيّم التشطيب والوزن والراحة",
    "Choose transparent delivery and service": "اختر خدمة وتوصيلًا بشروط واضحة",
    "Understand the Daytona silhouette": "تعرّف إلى تصميم دايتونا",
    "Choose the reference before the colour": "اختر الرقم المرجعي قبل اللون",
    "Read the chronograph dial": "اقرأ ميناء الكرونوغراف",
    "Assess fit on the wrist": "قيّم الملاءمة على المعصم",
    "Pick a configuration for your lifestyle": "اختر التكوين المناسب لأسلوب حياتك",
    "Build a two-minute after-wear routine": "اتبع روتين عناية لدقيقتين بعد الارتداء",
    "Manage heat and rapid temperature changes": "تعامل مع الحرارة والتغير السريع في درجات الحرارة",
    "Treat water resistance as a tested condition": "تعامل مع مقاومة الماء كحالة تحتاج إلى اختبار",
    "Protect the watch from impact and magnetism": "احمِ الساعة من الصدمات والمغناطيسية",
    "Store and service it intelligently": "خزّن الساعة وصُنها بطريقة ذكية",
    "Mechanical versus quartz": "الميكانيكية مقارنة بالكوارتز",
    "How automatic winding works": "كيف يعمل التعبئة الأوتوماتيكية",
    "Power reserve and beat rate": "احتياطي الطاقة ومعدل النبض",
    "What jewels and finishing do": "دور الجواهر والتشطيبات",
    "Use and maintain a mechanical movement": "استخدام الحركة الميكانيكية وصيانتها",
    "Case diameter is only the beginning": "قطر العلبة ليس سوى البداية",
    "Lug-to-lug controls wrist coverage": "المسافة بين العروات تحدد تغطية المعصم",
    "Thickness changes comfort": "السماكة تؤثر في الراحة",
    "Bracelet and strap sizing matter": "مقاس السوار والحزام مهم",
    "Choose proportion, not a rule": "اختر التناسب لا قاعدة ثابتة",
    "Start with your real calendar": "ابدأ بجدول حياتك الحقيقي",
    "Watch one: the dependable daily piece": "الساعة الأولى: خيار يومي موثوق",
    "Watch two: the refined option": "الساعة الثانية: الخيار الأنيق",
    "Watch three: the expressive piece": "الساعة الثالثة: القطعة الجريئة",
    "Make every addition earn its place": "اجعل كل إضافة تستحق مكانها",
    "The Watch": "عالم الساعات",
    "Journal": "المجلة",
    "detailed guides": "أدلة تفصيلية",
    "Independent education": "محتوى تثقيفي مستقل",
    "Updated weekly": "تحديث أسبوعي",
    "Featured": "مميز",
    "min read": "دقائق للقراءة",
    "Read article": "اقرأ المقال",
    "Read Article": "اقرأ المقال",
    "READ ARTICLE": "اقرأ المقال",
    "Read more →": "اقرأ المزيد ←",
    "CUSTOMER REVIEWS": "آراء العملاء",
    "REPUTATION IS": "السمعة هي",
    "EVERYTHING": "كل شيء",
    "Read verified testimonials from real watch collectors and enthusiasts who trusted our custom watch configurations.": "اقرأ شهادات موثقة من جامعي الساعات وعشاقها الحقيقيين الذين وثقوا في تكوينات ساعاتنا المخصصة.",
    "Fahad Al-Mansoori": "فهد المنصوري",
    "Dubai Marina, UAE": "دبي مارينا، الإمارات",
    "Watch Collector": "هاوي جمع الساعات",
    "Rolex Daytona Panda": "رولكس دايتونا باندا",
    "ROLEX DAYTONA PANDA": "رولكس دايتونا باندا",
    "Absolutely mind-blowing. I own a genuine Datejust, but I wanted a Daytona for daily wear without the risk. The weight, bezel luster, and mechanical chronograph sweep are identical. Hand-delivered in Dubai within 4 hours!": "أمر مذهل للغاية. أمتلك ساعة ديت جست أصلية، لكنني أردت دايتونا للاستخدام اليومي دون قلق. الوزن، ولمعان الإطار، وحركة الكرونوغراف الميكانيكية متطابقة تماماً. تم التوصيل اليدوي في دبي خلال 4 ساعات!",
    "Absolutely mind-blowing. I own a genuine Datejust, but I wanted a Daytona for daily wear without the risk. The weight, bezel luster, and mechanical chronograph sweep are identical. Hand-delivered in Dubai within 4 hours": "أمر مذهل للغاية. أمتلك ساعة ديت جست أصلية، لكنني أردت دايتونا للاستخدام اليومي دون قلق. الوزن، ولمعان الإطار، وحركة الكرونوغراف الميكانيكية متطابقة تماماً. تم التوصيل اليدوي في دبي خلال 4 ساعات!",
    "Lucas Sterling": "لوكاس ستيرلينغ",
    "London, UK": "لندن، المملكة المتحدة",
    "Finance Director": "مدير مالي",
    "Patek Philippe Nautilus 5711": "باتيك فيليب نوتيلوس 5711",
    "PATEK PHILIPPE NAUTILUS 5711": "باتيك فيليب نوتيلوس 5711",
    "I was skeptical about the 8.3mm thickness, but the proportions are excellent. It fits beautifully on wrist. The blue-grey gradient dial shifts beautifully in direct light. Direct WhatsApp ordering was fast and smooth.": "كنت متشككًا بشأن سُمك 8.3 مم، لكن الأبعاد ممتازة وتستقر على المعصم بانسيابية. الميناء المتدرج باللون الأزرق والرمادي يتغير بروعة تحت الضوء المباشر. الطلب عبر واتساب كان سريعاً وسلساً.",
    "Sarah Jenkins": "سارة جنكينز",
    "Los Angeles, USA": "لوس أنجلوس، الولايات المتحدة",
    "Creative Director": "مديرة إبداعية",
    "Rolex Datejust 41 Wimbledon": "رولكس ديت جست 41 ويمبلدون",
    "ROLEX DATEJUST 41 WIMBLEDON": "رولكس ديت جست 41 ويمبلدون",
    "The Wimbledon slate Roman dial is a masterpiece of precision. The fluted bezel catches light beautifully. Incredible premium customer service from their Dubai desk!": "ميناء ويمبلدون الروماني باللون الرمادي تحفة فنية من الدقة. الإطار المخدد يعكس الضوء بشكل رائع. خدمة عملاء ممتازة واستثنائية من مكتبهم في دبي!",
    "The Wimbledon slate Roman dial is a masterpiece of precision. The fluted bezel catches light beautifully. Incredible premium customer service from their Dubai desk": "ميناء ويمبلدون الروماني باللون الرمادي تحفة فنية من الدقة. الإطار المخدد يعكس الضوء بشكل رائع. خدمة عملاء ممتازة واستثنائية من مكتبهم في دبي!",
    "Khalid Bin-Fahd": "خالد بن فهد",
    "Riyadh, Saudi Arabia": "الرياض، المملكة العربية السعودية",
    "Business Owner": "رائد أعمال",
    "Audemars Piguet Royal Oak 15500": "أوديمار بيجيه رويال أوك 15500",
    "AUDEMARS PIGUET ROYAL OAK 15500": "أوديمار بيجيه رويال أوك 15500",
    "Unbelievable craftsmanship on the brushed stainless steel bracelet. The links slide smoothly without any friction, catching light beautifully. Fast courier delivery to Riyadh. Recommended 100%!": "حرفية لا تُصدق في سوار الفولاذ المقاوم للصدأ المصقول. الوصلات تنزلق بسلاسة دون أي احتكاك وتعكس الضوء بجمال. توصيل سريع إلى الرياض. أنصح بها 100%!",
    "Unbelievable craftsmanship on the brushed stainless steel bracelet. The links slide smoothly without any friction, catching light beautifully. Fast courier delivery to Riyadh. Recommended 100%": "حرفية لا تُصدق في سوار الفولاذ المقاوم للصدأ المصقول. الوصلات تنزلق بسلاسة دون أي احتكاك وتعكس الضوء بجمال. توصيل سريع إلى الرياض. أنصح بها 100%!",
    "Jean-Pierre Moreau": "جان بيير مورو",
    "Geneva, Switzerland": "جنيف، سويسرا",
    "Horological Enthusiast": "خبير ساعات",
    "Vacheron Constantin Overseas": "فاشيرون كونستانتين أوفرسيز",
    "VACHERON CONSTANTIN OVERSEAS": "فاشيرون كونستانتين أوفرسيز",
    "Living in Geneva, I appreciate quality watchmaking. The Maltese Cross bezel finish and the quick-release steel strap mechanism work exactly like the original. Truly exceptional copy quality.": "بإقامتي في جنيف، أقدر صناعة الساعات الراقية. تشطيب إطار صليب مالطا وآلية السوار الفولاذي سريعة الفك تعمل تماماً مثل الأصل. جودة ماستر كوبي استثنائية حقاً.",
    "Amara Okafor": "أمارا أوكافور",
    "Lagos, Nigeria": "لاغوس، نيجيريا",
    "Art Director": "مدير فني",
    "AP Royal Oak Double Balance Wheel": "أوديمار بيجيه رويال أوك دبل بالانس ويل",
    "AP ROYAL OAK DOUBLE BALANCE WHEEL": "أوديمار بيجيه رويال أوك دبل بالانس ويل",
    "The skeleton dial is breathtaking. You can see the double balance wheels beating in perfect synchronization. The gold plating color is exceptionally rich and heavy. Exceeded all expectations!": "الميناء المفرغ (سكلتون) يسحر الأنفاس. يمكنك رؤية عجلات التوازن المزدوجة تنبض بتزامن تام. لون الطلاء الذهبي ثري وثقيل للغاية. فاقت كل التوقعات!",
    "The skeleton dial is breathtaking. You can see the double balance wheels beating in perfect synchronization. The gold plating color is exceptionally rich and heavy. Exceeded all expectations": "الميناء المفرغ (سكلتون) يسحر الأنفاس. يمكنك رؤية عجلات التوازن المزدوجة تنبض بتزامن تام. لون الطلاء الذهبي ثري وثقيل للغاية. فاقت كل التوقعات!",
    "SWISS MOVEMENT 1:1": "حركة سويسرية ١:١",
    "Automatic Sweep Movement": "حركة مسح أوتوماتيكية",
    "VS3235 & Caliber 4130 Clones": "كاليبر VS3235 و4130 كلون",
    "Flawless Sweep & Chronograph": "مسح انسيابي وكرونوغراف متقن",
    "Highly Corrosion Resistant": "مقاوم للتآكل بدرجة عالية",
    "Genuine Luxury Weight": "وزن فاخر ومطابق للأصل",
    "Anti-Reflective Coating": "طبقة مانعة للانعكاس",
    "Scratch-Proof Durability": "متانة مقاومة للخدش",
    "THE MASTER COLLECTION": "المجموعة الرئيسية",
    "The Master Collection": "المجموعة الرئيسية",
    "The Master collection": "المجموعة الرئيسية",
    "THE SIGNATURE": "التشكيلة المميزة",
    "The Signature": "التشكيلة المميزة",
    "The signature": "التشكيلة المميزة",
    "CATALOGUE": "الكتالوج",
    "Catalogue": "الكتالوج",
    "Explore our comprehensive index of 1:1 luxury replica watches. Configured with genuine weights, exact dimensions, and premium materials to ensure zero distinction from local boutiques.": "استكشف فهرسنا الشامل لساعات الماستر كوبي الفاخرة ١:١. مصممة بأوزان أصلية، وأبعاد دقيقة، ومواد فائقة الجودة لضمان التطابق التام مع الساعات الأصلية.",
    "Search by model, brand, category, or ref...": "البحث عن طريق الموديل، الماركة، الفئة، أو الطراز...",
    "Reset Filters": "إعادة ضبط التصفية",
    "All Brands": "جميع الماركات",
    "All Categories": "جميع الفئات",
    "Womens": "نسائي",
    "Mens": "رجالي",
    "Sort By": "الترتيب حسب",
    "Default": "الافتراضي",
    "Price: Low to High": "السعر: من الأقل للأعلى",
    "Price: High to Low": "السعر: من الأعلى للأقل",
    "Showing": "عرض",
    "of": "من",
    "MASTER TIMEPIECES": "ساعات ماستر كوبي",
    "Master Timepieces": "ساعات ماستر كوبي",
    "SWISS QC STANDARDS GUARANTEED": "معايير الجودة السويسرية مضمونة",
    "Swiss QC Standards Guaranteed": "معايير الجودة السويسرية مضمونة",
    "View Specs": "عرض المواصفات",
    "Audemars Piguet": "أوديمار بيجيه",
    "AUDEMARS PIGUET": "أوديمار بيجيه",
    "Rolex": "رولكس",
    "ROLEX": "رولكس",
    "Patek Philippe": "باتيك فيليب",
    "PATEK PHILIPPE": "باتيك فيليب",
    "Richard Mille": "ريتشارد ميل",
    "RICHARD MILLE": "ريتشارد ميل",
    "Hublot": "هوبلو",
    "HUBLOT": "هوبلو",
    "Cartier": "كارتييه",
    "CARTIER": "كارتييه",
    "Vacheron Constantin": "فاشيرون كونستانتين",
    "VACHERON CONSTANTIN": "فاشيرون كونستانتين",
    "Breitling": "بريتلينغ",
    "BREITLING": "بريتلينغ",
    "Panerai": "بانيراي",
    "PANERAI": "بانيراي",
    "Roger Dubuis": "روجيه دوبوي",
    "ROGER DUBUIS": "روجيه دوبوي",
    "Chopard": "شوبارد",
    "CHOPARD": "شوبارد",
    "IWC": "آي دبليو سي",
    "Omega": "أوميغا",
    "OMEGA": "أوميغا",
    "TAG Heuer": "تاغ هوير",
    "TAG HEUER": "تاغ هوير",
    "Rafael Nadal": "رافائيل نادال",
    "Alexander Zverev": "ألكسندر زفيريف",
    "Sergio Ramos": "سيرخيو راموس",
    "Shah Rukh Khan": "شاه روخ خان",
    "Oracle Time": "أوراكل تايم",
    "ORACLE TIME": "أوراكل تايم",
    "Watch Paparazzi": "واتش باباراتزي",
    "GQ": "جي كيو",
    "Richard Mille RM 27-04 Tourbillon Rafael Nadal": "ريتشارد ميل RM 27-04 توربيون رافائيل نادال",
    "Richard Mille RM 67-02 Alexander Zverev": "ريتشارد ميل RM 67-02 ألكسندر زفيريف",
    "Patek Philippe Aquanaut Chronograph 5968A-001 Orange": "باتيك فيليب أكوانوت كرونوغراف 5968A-001 برتقالي",
    "Audemars Piguet Royal Oak Perpetual Calendar Blue Ceramic": "أوديمار بيغيه رويال أوك بالتقويم الدائم من السيراميك الأزرق",
    "Instagram": "إنستغرام",
    "IFL Watches": "آي إف إل واتشز",
    "Order Securely via WhatsApp": "اطلب بأمان عبر الواتساب",
    "Click to expand": "انقر للتكبير",
    "Hover to zoom · Click to expand": "مرر للتكبير · انقر للتوسيع",
    "Hover to zoom \\u00a0·\\u00a0 Click to expand": "مرر للتكبير · انقر للتوسيع",
    "Factory": "المصنع",
    "Case": "العلبة",
    "Casing": "العلبة",
    "Bezel": "الإطار",
    "Glass": "الزجاج",
    "Water Resistance": "مقاومة الماء",
    "Warranty": "الضمان",
    "Audience": "الفئة",
    "Product Overview": "نظرة عامة على المنتج",
    "Key Features": "الميزات الرئيسية",
    "Back to Catalogue": "العودة إلى الكتالوج",
    "Direct Hand-Delivery in UAE": "توصيل يدوي مباشر في الإمارات",
    "Free Delivery in Dubai": "توصيل مجاني في دبي",
    "2-Year Warranty Included": "ضمان سنتين مشمول",
    "Cash on Delivery Available": "الدفع عند الاستلام متاح",
    "CONTACT US": "اتصل بنا",
    "CUSTOMER SERVICE": "خدمة العملاء",
    "CHAT VIA WHATSAPP": "الدردشة عبر الواتساب",
    "CASH ON DELIVERY (GCC)": "الدفع عند الاستلام (الخليج)",
    "USD / CARD PAYMENTS": "الدفع بالدولار / البطاقات",
    "USD PAYMENTS": "الدفع بالدولار الأمريكي",
    "BANK TRANSFER": "تحويل بنكي",
    "Official Logistics Partners": "شركاء الخدمات اللوجستية الرسميون",
    "Official Couriers": "شركات الشحن الرسمية",
    "DHL, FEDEX & UPS": "دي إتش إل وفيديكس ويو بي إس",
    "DHL, UPS & FEDEX": "دي إتش إل ويو بي إس وفيديكس",
    "Global Insured Delivery via DHL • FedEx • UPS": "شحن دولي مؤمّن عبر دي إتش إل • فيديكس • يو بي إس",
    "Online Now": "متصل الآن",
    "Interested in this Timepiece?": "هل ترغب في اقتناء هذه الساعة؟",
    "Our Dubai team is online to share live HD wrist videos, confirm exact weight specifications, and arrange same-day delivery.": "فريقنا في دبي متواجد لمشاركة مقاطع فيديو حية عالية الدقة وتأكيد تفاصيل الوزن وترتيب التوصيل في نفس اليوم.",
    "Looking for a Specific Model?": "هل تبحث عن موديل محدد؟",
    "Whether you're looking for a Daytona, Royal Oak, Nautilus, or Richard Mille, our Dubai team can source and deliver your desired watch today.": "سواء كنت تبحث عن دايتونا أو رويال أوك أو نوتيلوس أو ريتشارد ميل، يمكن لفريقنا في دبي توفير وتسليم ساعتك المفضلة اليوم.",
    "Instant Sourcing Available": "التوفير الفوري متوفر",
    "AVAILABLE NOW / BUY NOW": "متوفر الآن / اطلب الآن",
    "Available Now / Buy Now": "متوفر الآن / اطلب الآن",
    "Available Now": "متوفر الآن",
    "Buy Now": "اطلب الآن",
    "2-Year Warranty": "ضمان سنتين",
    "Cash on Delivery": "الدفع عند الاستلام",
    "Same-Day Dubai Delivery": "توصيل في نفس اليوم بدبي",
    "Live Video Inspection": "فحص عبر فيديو حي عالي الدقة",
    "Chat on WhatsApp": "تحدث معنا عبر الواتساب",
    "Continue Browsing": "متابعة التصفح",
    "Maybe Later": "ربما لاحقاً",
    "© 2026 Dubai Watches Gallery. All rights reserved. Premium timepieces.": "© 2026 معرض دبي للساعات. جميع الحقوق محفوظة. ساعات فاخرة.",
    "© 2026 Dubai Watches Gallery. All rights reserved. 1:1 Swiss Clone replica timepieces.": "© 2026 معرض دبي للساعات. جميع الحقوق محفوظة. ساعات ماستر كوبي طبق الأصل ١:١.",
    "Rolex Watches": "ساعات رولكس",
    "Patek Philippe Watches": "ساعات باتيك فيليب",
    "Audemars Piguet Watches": "ساعات أوديمار بيجيه",
    "Richard Mille Watches": "ساعات ريتشارد ميل",
    "Rolex 1:1 Clones": "رولكس كلون ١:١",
    "Patek Philippe Clones": "باتيك فيليب كلون ١:١",
    "Audemars Piguet Clones": "أوديمار بيجيه كلون ١:١",
    "Richard Mille Clones": "ريتشارد ميل كلون ١:١",
    "OUR SPECIFICATIONS": "مواصفاتنا",
    "Clone Caliber Movement": "حركة كاليبر كلون",
    "904L Anti-Corrosive Steel": "فولاذ 904L المقاوم للصدأ",
    "Bespoke Bezel Finishes": "تشطيبات إطار مخصصة",
    "Ultra-Clear Sapphire Glass": "زجاج سافير فائق الوضوح",
    "DWG REPLICA ASSURANCE": "ضمان معرض دبي للساعات للجودة",
    "1:1 Weight Guarantee": "ضمان الوزن المطابق ١:١",
    "AAA+ Precision Sweeping": "حركة انسيابية دقيقة AAA+",
    "Indistinguishable Engravings": "نقوش مطابقة تماماً للأصل",
    "Dual Waterproof Seals": "أختام ثنائية لمقاومة الماء",
    "WhatsApp Order Desk": "مكتب طلبات واتساب",
    "QC Photo Review": "مراجعة صور الجودة (QC)",
    "GCC Secure Delivery": "توصيل آمن لدول الخليج",
    "Secure Packaging": "تغليف آمن",
    "Hi Dubai Watches Gallery! I'm visiting your website and would like to inquire about your premium watch collection.": "مرحبًا معرض دبي للساعات! أنا أزور موقعكم وأود الاستفسار عن مجموعة الساعات الفاخرة المتاحة لديكم.",
    "Hi Dubai Watches Gallery! I'm visiting your website and would like to inquire about your premium 1:1 Swiss Clone watch collection.": "مرحبًا معرض دبي للساعات! أنا أزور موقعكم وأود الاستفسار عن مجموعة ساعات الماستر كوبي الفاخرة.",

  }
};

export function translate(text: string, lang: string): string {
  if (!text) return '';
  if (lang !== 'ar') return text;
  
  const trimmed = text.trim();
  if (TRANSLATIONS.ar[trimmed]) {
    return TRANSLATIONS.ar[trimmed];
  }
  if (TRANSLATIONS.ar[text]) {
    return TRANSLATIONS.ar[text];
  }
  
  // Case-insensitive match fallback
  const lower = trimmed.toLowerCase();
  for (const [key, value] of Object.entries(TRANSLATIONS.ar)) {
    if (key.toLowerCase() === lower) {
      return value;
    }
  }

  return text;
}

export function translateUiText(text: string, lang = 'ar'): string {
  if (!text || lang !== 'ar') return text;

  const leading = text.match(/^\s*/)?.[0] || '';
  const trailing = text.match(/\s*$/)?.[0] || '';
  const value = text.trim();
  if (!value) return text;

  const direct = translate(value, 'ar');
  if (direct !== value) {
    return `${leading}${direct}${trailing}`;
  }

  const compoundReplacements: Array<[RegExp, string]> = [
    [/\bFeatured\b/gi, 'مميز'],
    [/\bmin read\b/gi, 'دقائق للقراءة'],
    [/\bmin\b/gi, 'دقائق'],
    [/\bdetailed guides\b/gi, 'أدلة تفصيلية'],
    [/\bIndependent education\b/gi, 'محتوى تثقيفي مستقل'],
    [/\bUpdated weekly\b/gi, 'تحديث أسبوعي'],
    [/\bSame-day delivery\b/gi, 'توصيل في نفس اليوم'],
    [/\bService warranty\b/gi, 'ضمان الخدمة'],
    [/\bMultiple payments\b/gi, 'طرق دفع متعددة'],
    [/\bVIEW SPECS\b/gi, 'عرض المواصفات'],
    [/\bVIEW COLLECTION\b/gi, 'عرض المجموعة'],
    [/\bREAD ARTICLE\b/gi, 'اقرأ المقال'],
    [/\bRead article\b/gi, 'اقرأ المقال'],
    [/\bRead Article\b/gi, 'اقرأ المقال'],
    [/\bExclusive Price\b/gi, 'السعر الحصري'],
    [/\bIn Stock\b/gi, 'متوفر'],
    [/\bSold Out\b/gi, 'نفد المخزون'],
    [/\bALL BRANDS\b/gi, 'جميع الماركات'],
    [/\bALL CATEGORIES\b/gi, 'جميع الفئات'],
    [/\bMENS\b/gi, 'رجالي'],
    [/\bWOMENS\b/gi, 'نسائي'],
  ];

  let translated = value;
  for (const [pattern, replacement] of compoundReplacements) {
    translated = translated.replace(pattern, replacement);
  }
  return translated === value ? text : `${leading}${translated}${trailing}`;
}
